In [9]:
#import pandas, numpy, seaborn, matplotlib

from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


C:\Users\Ted\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [10]:
trainDf = pd.read_csv('dataset/labeledTrainData.tsv', delimiter="\t", encoding='utf-8')
trainDf.head()

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

In [11]:
testDf = pd.read_csv('dataset/testData.tsv', delimiter="\t", encoding='utf-8')
testDf.head()

id                                             review
0  12311_10  Naturally in a film who's main themes are of m...
1    8348_2  This movie is a disaster within a disaster fil...
2    5828_4  All in all, this is a movie for kids. We saw i...
3    7186_2  Afraid of the Dark left me with the impression...
4   12128_7  A very accurate depiction of small time mob li...

In [12]:
trainDf["review"][0]

"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally sta

## Data clean up

### Removing stop words



In [13]:
#import and download stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ted\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
from nltk.corpus import stopwords
stops = stopwords.words('english')

In [15]:
import re

#Clean text
def clean(text):
    
    # Remove HTML markup
    textWithoutHtml = re.sub('<[^>]*>', '', text)
    
    #2 - Remove non-letters
    textWithoutNo = (re.sub("[^a-zA-Z]", " ", textWithoutHtml))
    
    #3 - Convert words to lower case and split them
    words = textWithoutNo.lower().split()
    
    #4 - Remove stop words
    words = [w for w in words if not w in stops]
    
    #5 - Return a list of words
    return (' '.join(words))

In [16]:
clean_reviews = trainDf.review.apply(lambda x : clean(x))
clean_reviews[0]

'stuff going moment mj started listening music watching odd documentary watched wiz watched moonwalker maybe want get certain insight guy thought really cool eighties maybe make mind whether guilty innocent moonwalker part biography part feature film remember going see cinema originally released subtle messages mj feeling towards press also obvious message drugs bad kay visually impressive course michael jackson unless remotely like mj anyway going hate find boring may call mj egotist consenting making movie mj fans would say made fans true really nice actual feature film bit finally starts minutes excluding smooth criminal sequence joe pesci convincing psychopathic powerful drug lord wants mj dead bad beyond mj overheard plans nah joe pesci character ranted wanted people know supplying drugs etc dunno maybe hates mj music lots cool things like mj turning car robot whole speed demon sequence also director must patience saint came filming kiddy bad sequence usually directors hate workin

In [17]:
#Convert a collection of text documents to a matrix of token counts
#Import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

#Initialize the "CountVectorizer" object
vectorizer = CountVectorizer(analyzer="word", tokenizer=None, preprocessor=None,stop_words=None, max_features=5000)
trained_bag = vectorizer.fit_transform(clean_reviews)

In [18]:
vectorizer.get_feature_names()

['abandoned',
 'abc',
 'abilities',
 'ability',
 'able',
 'abraham',
 'absence',
 'absent',
 'absolute',
 'absolutely',
 'absurd',
 'abuse',
 'abusive',
 'abysmal',
 'academy',
 'accent',
 'accents',
 'accept',
 'acceptable',
 'accepted',
 'access',
 'accident',
 'accidentally',
 'accompanied',
 'accomplished',
 'according',
 'account',
 'accuracy',
 'accurate',
 'accused',
 'achieve',
 'achieved',
 'achievement',
 'acid',
 'across',
 'act',
 'acted',
 'acting',
 'action',
 'actions',
 'activities',
 'actor',
 'actors',
 'actress',
 'actresses',
 'acts',
 'actual',
 'actually',
 'ad',
 'adam',
 'adams',
 'adaptation',
 'adaptations',
 'adapted',
 'add',
 'added',
 'adding',
 'addition',
 'adds',
 'adequate',
 'admire',
 'admit',
 'admittedly',
 'adorable',
 'adult',
 'adults',
 'advance',
 'advanced',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'advise',
 'affair',
 'affect',
 'affected',
 'afford',
 'aforementioned',
 'afraid',
 'africa',
 'african',
 'after

In [19]:
print(trained_bag.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
#initialize a Random Forest classifier with 100 trees - source from Github
forest = RandomForestClassifier(n_estimators = 100)

In [21]:
forest = forest.fit( trained_bag.toarray(), trainDf["sentiment"] )

In [22]:
test_reviews = testDf.review.apply(lambda x: clean(x))
test_reviews[0]

'naturally film main themes mortality nostalgia loss innocence perhaps surprising rated highly older viewers younger ones however craftsmanship completeness film anyone enjoy pace steady constant characters full engaging relationships interactions natural showing need floods tears show emotion screams show fear shouting show dispute violence show anger naturally joyce short story lends film ready made structure perfect polished diamond small changes huston makes inclusion poem fit neatly truly masterpiece tact subtlety overwhelming beauty'

In [23]:
tested_features = vectorizer.transform(test_reviews)
tested_bag = np.asarray(tested_features)

In [24]:
#Use the random forest to make sentiment label predictions
result = forest.predict(tested_features)

In [25]:
output = pd.DataFrame( data={"id":testDf["id"], "sentiment":result} )
output

id  sentiment
0      12311_10          1
1        8348_2          0
2        5828_4          1
3        7186_2          1
4       12128_7          1
5        2913_8          1
6        4396_1          0
7         395_2          1
8       10616_1          0
9        9074_9          1
10       9252_3          1
11       9896_9          1
12        574_4          1
13      11182_8          1
14      11656_4          1
15       2322_4          1
16       8703_1          1
17       7483_1          0
18      6007_10          1
19      12424_4          0
20       4672_1          0
21      10841_3          0
22       8954_7          1
23       7392_1          0
24      10288_8          1
25       5343_4          0
26       4950_1          0
27       9257_4          0
28       8689_3          0
29       4480_2          0
...         ...        ...
24970   6857_10          1
24971   11091_8          1
24972    4167_2          1
24973     679_4          1
24974   10147_1          0
24975    6875_1          0
24976    923_10          1
24977    6200_8          0
24978    7208_8          1
24979    5363_8          1
24980    4067_8          0
24981    1773_7          0
24982   1498_10          1
24983  10497_10          1
24984   3444_10          1
24985     588_2          0
24986    9678_9          1
24987    1983_9          0
24988    5012_3          0
24989   12240_2          1
24990    5071_2          0
24991    5078_2          0
24992   10069_3          0
24993    7407_8          1
24994    7207_1          0
24995   2155_10          1
24996     59_10          1
24997    2531_1          0
24998    7772_8          1
24999  11465_10          1

[25000 rows x 2 columns]

In [31]:
final_X = trainDf['sentiment']
final_y = testDf['review']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(final_X, final_y, test_size = 0.3, random_state = 101)

# we can check their dimension
print(X_train.shape)
print(X_test.shape)

(17500,)
(7500,)
